### ISSUE TITLE
Take a look at instructions

### ISSUE THREAD

**Issue by vfarinhaluz** [michaelpetersubc/cetc#4]
Hello Guys,
Please take a look at the instructions and let me know if there are any issues. If not, we can use these as instructions for the participants.
Vitor

**Comment by vfarinhaluz** [comment]
The file is here:
https://github.com/michaelpetersubc/cetc/blob/master/2020/CETC-instructions.md

**Comment by shunyanoda** [comment]
This looks perfect to me! I have nothing to suggest.
